Sleep 2.5s
Type "glocate -i"
Enter
Sleep 5s
Type "glocate "
Sleep 1.5s
Type '"'
Sleep 1s
Type "\"
Sleep 500ms
Type ".go"
Sleep 1s
Type '$"'
Enter
Sleep 5s
Up
Left
Sleep 500ms
Backspace 5
Sleep 1s
Type "YB"
Sleep 500ms
Type "al"
Sleep 1s
Enter
Sleep 1s
Up
Left 3
Sleep 500ms
Backspace 2
Type "yb"
Sleep 500ms
Backspace
Type "B"
Enter
Up
Left 3
Backspace
Type "b"
Sleep 1.5s
Enter
Sleep 3s
Type "# nice, smartcase"
Sleep 500ms
Type "!"
Sleep 2.5s
Ctrl+C
Sleep 1s
Ctrl+D

